
#include "jit/jit-alloc.c"
#include "jit/jit-apply-arm.c"
#include "jit/jit-apply-x86-64.c"
#include "jit/jit-apply-x86.c"
#include "jit/jit-apply.c"
#include "jit/jit-bitset.c"
#include "jit/jit-block.c"
#include "jit/jit-compile.c"
#include "jit/jit-context.c"
#include "jit/jit-cpuid-x86.c"
#include "jit/jit-debugger.c"
#include "jit/jit-dump.c"
#include "jit/jit-elf-read.c"
//#include "jit/jit-elf-write.c" // < included in extra1
#include "jit/jit-except.c"
#include "jit/jit-function.c"
#include "jit/jit-gen-arm.c"
#include "jit/jit-init.c"
#include "jit/jit-insn.c"
#include "jit/jit-interp-opcode.c"
#include "jit/jit-interp.c"
#include "jit/jit-intrinsic.c"
#include "jit/jit-live.c"
#include "jit/jit-memory-cache.c"
#include "jit/jit-memory.c"
#include "jit/jit-meta.c"
#include "jit/jit-objmodel.c"
#include "jit/jit-opcode-apply.c"
#include "jit/jit-opcode.c" // < to regenerate for x86 and arm
#include "jit/jit-pool.c"
#include "jit/jit-reg-alloc.c"
#include "jit/jit-reg-class.c"
#include "jit/jit-rules-arm.c"
#include "jit/jit-rules-interp.c"
#include "jit/jit-rules-x86-64.c"
#include "jit/jit-rules-x86.c"
#include "jit/jit-rules.c"
#include "jit/jit-signal.c"
//#include "jit/jit-symbol.c" // < included in extra2
#include "jit/jit-thread.c"
#include "jit/jit-type.c"
#include "jit/jit-unwind.c"
#include "jit/jit-util.c"
#include "jit/jit-value.c"
#include "jit/jit-varint.c"
#include "jit/jit-vmem.c"
#include "jit/jit-walk.c"
